from datetime import datetime
import helics as h
from dots_infrastructure.DataClasses import TimeStepInformation, EsdlId, HelicsCalculationInformation, PublicationDescription, SubscriptionDescription
from dots_infrastructure.HelicsFederateHelpers import HelicsSimulationExecutor
from esdl import EnergySystem

# This file is generated, DO NOT edit this file!

class ExampleBatteryServiceBase(HelicsSimulationExecutor):

    def __init__(self):
        super().__init__()

        
        # Calculation: max_charge_and_discharge
        max_charge_and_discharge_inputs = [
        
        ]
        max_charge_and_discharge_outputs = [
        
            PublicationDescription(global_flag=True, 
                                    esdl_type="Battery",
                                    output_name="max_charge_active_power",
                                    output_unit="W", 
                                    data_type=h.HelicsDataType.DOUBLE),
            PublicationDescription(global_flag=True, 
                                    esdl_type="Battery",
                                    output_name="max_discharge_active_power",
                                    output_unit="W", 
                                    data_type=h.HelicsDataType.DOUBLE),
        ]
        max_charge_and_discharge_information = HelicsCalculationInformation(
            time_period_in_seconds=900,
            offset=0, 
            uninterruptible=False, 
            wait_for_current_time_update=False, 
            terminate_on_error=True, 
            calculation_name="max_charge_and_discharge", 
            inputs=max_charge_and_discharge_inputs, 
            outputs=max_charge_and_discharge_outputs, 
            calculation_function=self.max_charge_and_discharge
        )
        self.add_calculation(max_charge_and_discharge_information)
        # Calculation: charge_battery
        charge_battery_inputs = [
        
            SubscriptionDescription(esdl_type="EConnection", 
                                    input_name="active_power_to_charge", 
                                    input_unit="W", 
                                    input_type=h.HelicsDataType.DOUBLE),
        ]
        charge_battery_outputs = [
        
        ]
        charge_battery_information = HelicsCalculationInformation(
            time_period_in_seconds=900,
            offset=0, 
            uninterruptible=False, 
            wait_for_current_time_update=False, 
            terminate_on_error=True, 
            calculation_name="charge_battery", 
            inputs=charge_battery_inputs, 
            outputs=charge_battery_outputs, 
            calculation_function=self.charge_battery
        )
        self.add_calculation(charge_battery_information)

    
    def max_charge_and_discharge(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        pass
    
    def charge_battery(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        pass
    